language: python

python:
- '3.6'

env:
    - SERVER=206.189.28.152

services:
- postgresql
- redis-server

before_script:
- pipenv run python client_api/manage.py migrate
- pipenv run python client_api/manage.py test

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/market-platform root@206.189.28.152:/root/market-platform
  on:
    branch: master

before_install:
- psql -c `create database market_platform_backend;` -U postgres
- openssl aes-256-cbc -K $encrypted_480b6785672e_key -iv $encrypted_480b6785672e_iv
  -in deploy-key.enc -out ./deploy-key -d
- chmod 600 ./deploy-key
- ssh-add ./deploy-key
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy-key
- echo -e "Host $SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy-key
# - ssh -i ./deploy-key root@206.189.28.152 pwd

install:
    - python -m pip install pipenv
    - pipenv install
