version: "3.6"
services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client-api
    networks:
      - default

  redis:
    image: redis:latest
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - default

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: market_platform_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
    expose:
      - 5432
    networks:
      - default
    volumes:
      - "/var/volumes/postgres/:/var/lib/postgresql/data"

  flask:
    build:
      context: emulation
      dockerfile: ./Dockerfile
    restart: unless-stopped
    expose:
      - 5000
    networks:
      - default
    environment:
      - DOCKER=true
    depends_on:
      - redis
      - postgres

  client-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    expose:
      - 8000
    environment:
      - DOCKER=true
    networks:
      - default
    depends_on:
      - postgres
      - redis

networks:
  default:
